HOST_IP = "localhost"
USER = "root"
PASSWORD = "Curt!s74"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-data-collection@ttn"
MQTT_API_KEY = "NNSXS.IDXONJACSLAZZMLIRTQZXMA2ZDUFGMJC5KT4FNA.IRHRGSH6K7CHYEAL7WZIC2XW7QURBXA4WTHBG6IGNRWR4QGROFLQ"
MQTT_PORT = 1883
MQTT_TOPIC = "#"

